### PR TITLE
fix: updated pluralization in a few spots

### LINKED ISSUE #214: Incorrect Pluralization when there's only 1 combo
In the metadata section, when there's exactly 1 deck with the combo in it on EDHRec, it says "In 1 decks according to EDHREC." when it should say "In 1 deck according to EDHREC."

### PR DESCRIPTION
**Pull request by fearphage**
Fixes #214

### CODE REVIEW

File: components/search/ComboResults.vue [hunk 1]
```diff
@@ -91,11 +91,9 @@ export default Vue.extend({
...
         }
 
-        if (combo.numberOfEDHRECDecks === 1) {
-          return "1 deck (EDHREC)";
-        }
-
-        return `${combo.numberOfEDHRECDecks} decks (EDHREC)`;
+        return `${combo.numberOfEDHRECDecks} deck${
+          combo.numberOfEDHRECDecks === 1 ? "" : "s"
+        } (EDHREC)`;
```
Comment (crookedneighbor) [inline components/search/ComboResults.vue:96]: This is fewer lines of code, but I find the previous way this displayed to be a lot more readable. Can you talk to me about the merits of changing it to this?

Comment (fearphage) [reply components/search/ComboResults.vue:96]: I'm not really concerned with the brevity of the code. I think the largest thing it adds is consistency. I don't find value in doing things different ways in different places. Everywhere something is pluralized, it should follow the same pattern. This is largely how most internationalization libraries function so this is what I went to. I could extract this into a pluralization helper (as inspired by i18n libraries) if you prefer:

```js
const pluralize = (word, count, alternative) => count === 1 
  ? word
   : (alternative || word + 's')
 ;
```

Usage:

```js
`... ${helpers.pluralize('deck', combo.numerOfEDHRECDecks)} ...`
`... ${helpers.pluralize('box'. count, 'boxes')} ...`
```

Comment (crookedneighbor) [reply components/search/ComboResults.vue:96]: I'd be fine pulling this out into a pluralize helper method. Want to go that route for this PR?

If not, I can do it as a refactor after this gets merged.

File: test/pages/combo/_id.test.ts [hunk 2]
```diff
@@ -304,6 +304,43 @@ describe("ComboPage", () => {
     ]);
   });
 
+  it("Pluralizes number of decks correctly", async () => {
```
Comment (crookedneighbor) [inline test/pages/combo/_id.test.ts:307]:
```suggestion
  it("pluralizes number of decks correctly", async () => {
```

File: test/pages/combo/_id.test.ts [hunk 3]
```diff
@@ -304,6 +304,43 @@ describe("ComboPage", () => {
...
+      numberOfDecks: 1,
+    });
+
+    const lists = wrapper.findAllComponents(ComboListStub);
+
+    expect(lists).toHaveLength(5);
+
+    expect(lists.at(4).props("iterations")).toEqual([
+      "In 1 deck according to EDHREC.",
+    ]);
```
Comment (crookedneighbor) [inline test/pages/combo/_id.test.ts:341]: I believe this will work:

```suggestion
    const metadata = lists.at(4);
    
    expect(metadata.props("iterations")).toEqual([
      "In 1 deck according to EDHREC.",
    ]);

    await wrapper.setData({
      numberOfDecks: 2
    });
    
    expect(metadata.props("iterations")).toEqual([
      "In 2 decks according to EDHREC.",
    ]);
```

**Review by crookedneighbor — CHANGES_REQUESTED** [review]
Thanks for adding the test! I was going to ask for that, so happy to see it there.

File: components/search/ComboResults.vue (hunk 1 above)
Comment (fearphage) [reply components/search/ComboResults.vue:96]: Is there already a location to place these helpers/utils?

File: test/pages/combo/_id.test.ts (hunk 3 above)
Comment (fearphage) [reply test/pages/combo/_id.test.ts:341]: The previous test already tests with 14 decks. That's why I didn't duplicate that test.

Comment (crookedneighbor) [reply test/pages/combo/_id.test.ts:341]: Fair enough!

File: components/search/ComboResults.vue (hunk 1 above)
Comment (crookedneighbor) [reply components/search/ComboResults.vue:96]: Let's leave that for a followup PR. I'm debating about whether it should just live in `lib` or be a plugin.
